import type { Metadata } from "next"
import { Kanit } from "next/font/google"
import "./globals.css"
import TopMenu from "@/components/TopMenu"
import { getServerSession } from "next-auth"
import { authOptions } from "./api/auth/[...nextauth]/authOptions"
import NextAuthProvider from "@/provider/NextAuthProvider"

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-kanit",
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Lawyer App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <head>
        {/* ✅ Make sure viewport is set for mobile responsiveness */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${kanit.variable} antialiased text-gray-900`}>
        <NextAuthProvider session={session}>
          <TopMenu />
          <main className="min-h-screen w-full px-4 sm:px-6 md:px-8 lg:px-12">
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  )
}