import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import TopMenu from "@/components/TopMenu";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import NextAuthProvider from "@/provider/NextAuthProvider";

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-kanit",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const nextAuthSession = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body
        className={`${kanit.variable} antialiased`}
      >
        <NextAuthProvider session={ nextAuthSession}>
        <TopMenu/>
        {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
